---
# config github

- name: Generate github key
  expect:
    command: ssh-keygen -t rsa -C {{ hostvars[inventory_hostname].git_email }}
    echo: true
    creates: "{{ git_key_file }}"
    responses:
      Enter file: ""
      Enter passphrase: "{{ hostvars[inventory_hostname].git_pass }}"
      Enter same passphrase: "{{ hostvars[inventory_hostname].git_pass }}"
      (?i)Overwrite: "{{ overwrite_response }}"

- name: Read SSH public key to authorize
  command: cat "{{ git_key_file }}.pub"
  register: git_pub_key
  changed_when: false


- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: Access Key for Some Machine
    token: '{{ github_access_token }}'
    pubkey: '{{ git_pub_key.stdout }}'


- name: git config --global user.name "your name"
  git_config:
    scope: global
    name: user.name
    value: "{{ hostvars[inventory_hostname].git_user }}"

- name: git config --global user.email you@example.com
  git_config:
    scope: global
    name: user.email
    value: "{{ hostvars[inventory_hostname].git_email }}"

- name: git config --global credential.helper "store type"
  git_config:
    scope: global
    name: credential.helper
    value: store
